# Generated by Django 5.0.6 on 2024-07-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_descripion', models.TextField(max_length=255)),
                ('long_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m')),
                ('slug', models.SlugField(unique=True)),
                ('marketing_price', models.FloatField()),
                ('promocional_marketing_price', models.FloatField(default=0)),
                ('type_product', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
