# Generated by Django 5.0.6 on 2024-07-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_descripion',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1),
        ),
    ]
